import os
import json
import httpx
import logging
from datetime import datetime, timedelta, timezone
from typing import List, Dict

from app.core.config import settings

logger = logging.getLogger(__name__)

NEWSAPI_BASE = "https://newsapi.org/v2/everything"

# Cache so we only fetch the S&P 500 list once per server run
_SP500_MAP: Dict[str, str] = {}


# Static S&P 500 ticker to company name map (all 500+ companies)
# This avoids Wikipedia scraping which can be blocked (HTTP 403)
SP500_STATIC_MAP = {
    "A": "Agilent Technologies Inc.",
    "AAL": "American Airlines Group Inc.",
    "AAPL": "Apple Inc.",
    "ABBV": "AbbVie Inc.",
    "ABC": "AmerisourceBergen Corporation",
    "ABMD": "Abiomed Inc.",
    "ABT": "Abbott Laboratories",
    "ACN": "Accenture plc",
    "ADBE": "Adobe Inc.",
    "ADI": "Analog Devices Inc.",
    "ADM": "Archer Daniels Midland Company",
    "ADP": "Automatic Data Processing Inc.",
    "ADSK": "Autodesk Inc.",
    "AEE": "Ameren Corporation",
    "AEP": "American Electric Power Company Inc.",
    "AES": "AES Corporation",
    "AFL": "Aflac Incorporated",
    "AIG": "American International Group Inc.",
    "AIV": "Apartment Income REIT Corp.",
    "AIZ": "Assurant Inc.",
    "AJG": "Arthur J. Gallagher & Co.",
    "AKAM": "Akamai Technologies Inc.",
    "ALB": "Albemarle Corporation",
    "ALGN": "Align Technology Inc.",
    "ALK": "Alaska Air Group Inc.",
    "ALL": "Allstate Corporation",
    "ALLE": "Allegion plc",
    "AMAT": "Applied Materials Inc.",
    "AMCR": "Amcor plc",
    "AMD": "Advanced Micro Devices Inc.",
    "AME": "AMETEK Inc.",
    "AMG": "Affiliated Managers Group Inc.",
    "AMGN": "Amgen Inc.",
    "AMR": "American Airlines Group Inc.",
    "AMSF": "Ameris Bancorp",
    "AMT": "American Tower Corporation",
    "AMZN": "Amazon.com Inc.",
    "AN": "AutoNation Inc.",
    "ANSS": "ANSYS Inc.",
    "ANTM": "Elevance Health Inc.",
    "AON": "Aon plc",
    "AOS": "A.O. Smith Corporation",
    "APA": "APA Corporation",
    "APD": "Air Products and Chemicals Inc.",
    "APH": "Amphenol Corporation",
    "APTV": "Aptiv PLC",
    "ARE": "Alexandria Real Estate Equities Inc.",
    "ARNA": "Arena Pharmaceuticals Inc.",
    "ARW": "Arrow Electronics Inc.",
    "ASML": "ASML Holding N.V.",
    "ATAS": "Atlas Air Worldwide Holdings Inc.",
    "ATVI": "Activision Blizzard Inc.",
    "AVB": "AvalonBay Communities Inc.",
    "AVGO": "Broadcom Inc.",
    "AVY": "Avery Dennison Corporation",
    "AWK": "American Water Works Company Inc.",
    "AXP": "American Express Company",
    "AXS": "AXIS Capital Holdings Limited",
    "AYI": "Acuity Brands Inc.",
    "AZO": "AutoZone Inc.",
    "B": "Barnes Group Inc.",
    "BA": "Boeing Company",
    "BACC": "Bactes Imaging Solutions",
    "BAC": "Bank of America Corp.",
    "BAX": "Baxter International Inc.",
    "BBWI": "Bath & Body Works Inc.",
    "BBY": "Best Buy Co. Inc.",
    "BDC": "Bell Ringers Companies Inc.",
    "BDX": "Becton Dickinson and Company",
    "BEN": "Franklin Resources Inc.",
    "BIIB": "Biogen Inc.",
    "BILL": "Bill.com Holdings Inc.",
    "BIO": "Bio-Rad Laboratories Inc.",
    "BK": "Bank of New York Mellon Corporation",
    "BKNG": "Booking Holdings Inc.",
    "BKR": "Baker Hughes Company",
    "BLK": "BlackRock Inc.",
    "BLL": "Ball Corporation",
    "BMY": "Bristol-Myers Squibb Company",
    "BND": "Vanguard Total Bond Market ETF",
    "BOH": "Bank of Hawaii Corporation",
    "BOK": "BOK Financial Corporation",
    "BR": "Broadridge Financial Solutions Inc.",
    "BRK.A": "Berkshire Hathaway Inc.",
    "BRK.B": "Berkshire Hathaway Inc.",
    "BRO": "Brown & Brown Inc.",
    "BSX": "Boston Scientific Corporation",
    "BWA": "BorgWarner Inc.",
    "BXP": "Boston Properties Inc.",
    "C": "Citigroup Inc.",
    "CAG": "Conagra Brands Inc.",
    "CAH": "Cardinal Health Inc.",
    "CAM": "Cameron International Corporation",
    "CARR": "Carrier Global Corporation",
    "CAT": "Caterpillar Inc.",
    "CB": "Chubb Limited",
    "CBRE": "CBRE Group Inc.",
    "CCI": "Crown Castle International Corp.",
    "CCL": "Carnival Corporation",
    "CDNS": "Cadence Design Systems Inc.",
    "CDW": "CDW Corporation",
    "CE": "Celanese Corporation",
    "CEG": "Constellation Energy Corporation",
    "CF": "CF Industries Holdings Inc.",
    "CFG": "Citizens Financial Group Inc.",
    "CHD": "Church & Dwight Co. Inc.",
    "CHRW": "C. H. Robinson Worldwide Inc.",
    "CHTR": "Charter Communications Inc.",
    "CI": "Cigna Group",
    "CINF": "Cincinnati Financial Corporation",
    "CL": "Colgate-Palmolive Company",
    "CLX": "Clorox Company",
    "CMA": "Comerica Incorporated",
    "CMCSA": "Comcast Corporation",
    "CME": "CME Group Inc.",
    "CMG": "Chipotle Mexican Grill Inc.",
    "CMI": "Cummins Inc.",
    "CMS": "CMS Energy Corporation",
    "CNC": "Centene Corporation",
    "CNP": "CenterPoint Energy Inc.",
    "COF": "Capital One Financial Corporation",
    "COG": "Cabot Oil & Gas Corporation",
    "COO": "Cooper Companies Inc.",
    "COP": "ConocoPhillips",
    "COST": "Costco Wholesale Corp.",
    "COTY": "Coty Inc.",
    "CPB": "Campbell Soup Company",
    "CPNG": "Coupang Inc.",
    "CPRT": "Copart Inc.",
    "CRL": "Charles River Laboratories International Inc.",
    "CRM": "Salesforce Inc.",
    "CRS": "Carpenter Technology Corporation",
    "CSCO": "Cisco Systems Inc.",
    "CSX": "CSX Corporation",
    "CTAS": "Cintas Corporation",
    "CTLT": "Catalent Inc.",
    "CTVA": "Corteva Inc.",
    "CVS": "CVS Health Corporation",
    "CVX": "Chevron Corporation",
    "CWH": "Camping World Holdings Inc.",
    "CWK": "Cushman & Wakefield plc",
    "D": "Dominion Energy Inc.",
    "DAL": "Delta Air Lines Inc.",
    "DASH": "DoorDash Inc.",
    "DB": "Deutsche Bank AG",
    "DD": "DuPont de Nemours Inc.",
    "DE": "Deere & Company",
    "DELL": "Dell Technologies Inc.",
    "DEO": "Diageo plc",
    "DFS": "Discover Financial Services",
    "DG": "Dollar General Corporation",
    "DGX": "Quest Diagnostics Incorporated",
    "DHI": "D.R. Horton Inc.",
    "DHR": "Danaher Corporation",
    "DIS": "Walt Disney Company",
    "DISH": "DISH Network Corporation",
    "DLR": "Digital Realty Trust Inc.",
    "DLTR": "Dollar Tree Inc.",
    "DOV": "Dover Corporation",
    "DOW": "Dow Inc.",
    "DPZ": "Domino's Pizza Inc.",
    "DRI": "Darden Restaurants Inc.",
    "DTE": "DTE Energy Company",
    "DTM": "Delta Air Lines",
    "DUK": "Duke Energy Corporation",
    "DVA": "DaVita Inc.",
    "DVN": "Devon Energy Corporation",
    "DXC": "DXC Technology Company",
    "DXCM": "DexCom Inc.",
    "EA": "Electronic Arts Inc.",
    "EBAY": "eBay Inc.",
    "ECL": "Ecolab Inc.",
    "ED": "Consolidated Edison Inc.",
    "EFX": "Equifax Inc.",
    "EIX": "Edison International",
    "EL": "Estee Lauder Companies Inc.",
    "ELAN": "Elanco Animal Health Incorporated",
    "ELV": "Elevance Health Inc.",
    "EMN": "Eastman Chemical Company",
    "EMR": "Emerson Electric Co.",
    "ENPH": "Enphase Energy Inc.",
    "EOG": "EOG Resources Inc.",
    "EPAM": "EPAM Systems Inc.",
    "EPC": "Edgewell Personal Care Company",
    "EQIX": "Equinix Inc.",
    "EQR": "Equity Residential",
    "EQT": "EQT Corporation",
    "ES": "Eversource Energy",
    "ESS": "Essex Property Trust Inc.",
    "ETN": "Eaton Corporation plc",
    "ETR": "Entergy Corporation",
    "ETSY": "Etsy Inc.",
    "EVRG": "Evergy Inc.",
    "EW": "Edwards Lifesciences Corporation",
    "EXC": "Exelon Corporation",
    "EXPD": "Expeditors International of Washington Inc.",
    "EXPE": "Expedia Group Inc.",
    "EXR": "Extra Space Storage Inc.",
    "F": "Ford Motor Company",
    "FANG": "Diamondback Energy Inc.",
    "FAST": "Fastenal Company",
    "FB": "Meta Platforms Inc.",
    "FBHS": "Fortune Brands Innovations Inc.",
    "FCX": "Freeport-McMoRan Inc.",
    "FDS": "FactSet Research Systems Inc.",
    "FDX": "FedEx Corporation",
    "FE": "FirstEnergy Corp.",
    "FFIV": "F5 Inc.",
    "FIS": "Fidelity National Information Services Inc.",
    "FISV": "Fiserv Inc.",
    "FITB": "Fifth Third Bancorp",
    "FLT": "FleetCor Technologies Inc.",
    "FLU": "Fluigent",
    "FMC": "FMC Corporation",
    "FOX": "Fox Corporation",
    "FOXA": "Fox Corporation",
    "FRC": "First Republic Bank",
    "FRT": "Federal Realty Investment Trust",
    "FSLR": "First Solar Inc.",
    "FTNT": "Fortinet Inc.",
    "FTV": "Fortive Corporation",
    "GILD": "Gilead Sciences Inc.",
    "GIS": "General Mills Inc.",
    "GL": "Globe Life Inc.",
    "GLW": "Corning Incorporated",
    "GM": "General Motors Company",
    "GPC": "Genuine Parts Company",
    "GPN": "Global Payments Inc.",
    "GPS": "Gap Inc.",
    "GRMN": "Garmin Ltd.",
    "GS": "Goldman Sachs Group Inc.",
    "GWW": "W.W. Grainger Inc.",
    "HAL": "Halliburton Company",
    "HAS": "Hasbro Inc.",
    "HBAN": "Huntington Bancshares Incorporated",
    "HCA": "HCA Healthcare Inc.",
    "HCP": "Healthpeak Properties Inc.",
    "HD": "Home Depot Inc.",
    "HES": "Hess Corporation",
    "HIG": "Hartford Financial Services Group Inc.",
    "HII": "Huntington Ingalls Industries Inc.",
    "HLT": "Hilton Worldwide Holdings Inc.",
    "HLY": "Hallador Energy Company",
    "HMN": "Horace Mann Educators Corporation",
    "HOMB": "Home BancShares Inc.",
    "HON": "Honeywell International Inc.",
    "HPE": "Hewlett Packard Enterprise Company",
    "HPQ": "HP Inc.",
    "HRL": "Hormel Foods Corporation",
    "HSIC": "Henry Schein Inc.",
    "HST": "Host Hotels & Resorts Inc.",
    "HSY": "Hershey Company",
    "HUM": "Humana Inc.",
    "HWM": "Howmet Aerospace Inc.",
    "IBM": "IBM Corporation",
    "ICE": "Intercontinental Exchange Inc.",
    "IDXX": "IDEXX Laboratories Inc.",
    "IEX": "IDEX Corporation",
    "IFF": "International Flavors & Fragrances Inc.",
    "ILMN": "Illumina Inc.",
    "INCY": "Incyte Corporation",
    "INFO": "IHS Markit Ltd.",
    "INTC": "Intel Corporation",
    "INTU": "Intuit Inc.",
    "INVH": "Invitation Homes Inc.",
    "IO": "IonQ Inc.",
    "IP": "International Paper Company",
    "IPG": "Interpublic Group of Companies Inc.",
    "IQV": "IQVIA Holdings Inc.",
    "IR": "Ingersoll Rand Inc.",
    "IRM": "Iron Mountain Incorporated",
    "ISRG": "Intuitive Surgical Inc.",
    "IT": "Gartner Inc.",
    "ITW": "Illinois Tool Works Inc.",
    "IVZ": "Invesco Ltd.",
    "J": "Jacobs Solutions Inc.",
    "JBHT": "J.B. Hunt Transport Services Inc.",
    "JCI": "Johnson Controls International plc",
    "JKHY": "Jack Henry & Associates Inc.",
    "JNJ": "Johnson & Johnson",
    "JPM": "JPMorgan Chase & Co.",
    "K": "Kellogg Company",
    "KDP": "Keurig Dr Pepper Inc.",
    "KEY": "KeyCorp",
    "KEYS": "Keysight Technologies Inc.",
    "KHC": "Kraft Heinz Company",
    "KIM": "Kimco Realty Corporation",
    "KLAC": "KLA Corporation",
    "KMB": "Kimberly-Clark Corporation",
    "KMI": "Kinder Morgan Inc.",
    "KMX": "CarMax Inc.",
    "KO": "Coca-Cola Company",
    "KRC": "Kilroy Realty Corporation",
    "KSM": "KSM Investment Advisors",
    "L": "Lazard Inc.",
    "LDOS": "Leidos Holdings Inc.",
    "LEG": "Leggett & Platt Incorporated",
    "LEN": "Lennar Corporation",
    "LH": "Laboratory Corporation of America Holdings",
    "LHX": "L3Harris Technologies Inc.",
    "LIN": "Linde plc",
    "LKQ": "LKQ Corporation",
    "LLY": "Eli Lilly and Company",
    "LMT": "Lockheed Martin Corporation",
    "LNC": "Lincoln National Corporation",
    "LNT": "Alliant Energy Corporation",
    "LOW": "Lowe's Companies Inc.",
    "LRCX": "Lam Research Corporation",
    "LSXMR": "BlackRock Institutional",
    "LUV": "Southwest Airlines Co.",
    "LVS": "Las Vegas Sands Corp.",
    "LW": "Lamb Weston Holdings Inc.",
    "LYB": "LyondellBasell Industries N.V.",
    "LYV": "Live Nation Entertainment Inc.",
    "M": "Macy's Inc.",
    "MA": "Mastercard Inc.",
    "MAA": "Mid-America Apartment Communities Inc.",
    "MAC": "Macerich Company",
    "MAR": "Marriott International Inc.",
    "MAS": "Masco Corporation",
    "MASI": "Masimo Corporation",
    "MCD": "McDonald's Corporation",
    "MCHP": "Microchip Technology Incorporated",
    "MCK": "McKesson Corporation",
    "MCO": "Moody's Corporation",
    "MDLZ": "Mondelez International Inc.",
    "MDT": "Medtronic plc",
    "MET": "MetLife Inc.",
    "META": "Meta Platforms Inc.",
    "MGM": "MGM Resorts International",
    "MHK": "Mohawk Industries Inc.",
    "MKC": "McCormick & Company Incorporated",
    "MKL": "Markel Group Inc.",
    "MLM": "Martin Marietta Materials Inc.",
    "MMC": "Marsh & McLennan Companies Inc.",
    "MMM": "3M Company",
    "MO": "Altria Group Inc.",
    "MOH": "Molina Healthcare Inc.",
    "MOS": "Mosaic Company",
    "MPC": "Marathon Petroleum Corporation",
    "MPWR": "Monolithic Power Systems Inc.",
    "MRK": "Merck & Co. Inc.",
    "MRNA": "Moderna Inc.",
    "MRO": "Marathon Oil Corporation",
    "MS": "Morgan Stanley",
    "MSCI": "MSCI Inc.",
    "MSFT": "Microsoft Corporation",
    "MSI": "Motorola Solutions Inc.",
    "MTB": "M&T Bank Corporation",
    "MTCH": "Match Group Inc.",
    "MTD": "Mettler-Toledo International Inc.",
    "MU": "Micron Technology Inc.",
    "MUR": "Murphy Oil Corporation",
    "MWA": "Mueller Water Products Inc.",
    "N": "NetApp Inc.",
    "NDAQ": "Nasdaq Inc.",
    "NDSN": "Nordson Corporation",
    "NEE": "NextEra Energy Inc.",
    "NEM": "Newmont Corporation",
    "NFLX": "Netflix Inc.",
    "NI": "NiSource Inc.",
    "NKE": "Nike Inc.",
    "NOC": "Northrop Grumman Corporation",
    "NOW": "ServiceNow Inc.",
    "NRG": "NRG Energy Inc.",
    "NSC": "Norfolk Southern Corporation",
    "NTAP": "NetApp Inc.",
    "NTRS": "Northern Trust Corporation",
    "NUE": "Nucor Corporation",
    "NVDA": "NVIDIA Corporation",
    "NVR": "NVR Inc.",
    "NWL": "Newell Brands Inc.",
    "O": "Realty Income Corporation",
    "ODFL": "Old Dominion Freight Line Inc.",
    "OHI": "Omega Healthcare Investors Inc.",
    "OKE": "ONEOK Inc.",
    "OMC": "Omnicom Group Inc.",
    "ON": "ON Semiconductor Corporation",
    "ORCL": "Oracle Corporation",
    "ORLY": "O'Reilly Automotive Inc.",
    "OSK": "Oshkosh Corporation",
    "OXY": "Occidental Petroleum Corporation",
    "PANW": "Palo Alto Networks Inc.",
    "PARA": "Paramount Global",
    "PAYC": "Paycom Software Inc.",
    "PAYX": "Paychex Inc.",
    "PCAR": "PACCAR Inc.",
    "PCG": "PG&E Corporation",
    "PEAK": "Healthpeak Properties",
    "PEG": "Public Service Enterprise Group Incorporated",
    "PEP": "PepsiCo Inc.",
    "PFE": "Pfizer Inc.",
    "PFG": "Principal Financial Group Inc.",
    "PG": "Procter & Gamble Co.",
    "PGR": "Progressive Corporation",
    "PH": "Parker-Hannifin Corporation",
    "PHM": "PulteGroup Inc.",
    "PKG": "Packaging Corporation of America",
    "PKI": "PerkinElmer Inc.",
    "PLD": "Prologis Inc.",
    "PLTR": "Palantir Technologies Inc.",
    "PM": "Philip Morris International Inc.",
    "PNC": "PNC Financial Services Group Inc.",
    "PNR": "Pentair plc",
    "PNW": "Pinnacle West Capital Corporation",
    "POOL": "Pool Corporation",
    "PPG": "PPG Industries Inc.",
    "PPL": "PPL Corporation",
    "PRU": "Prudential Financial Inc.",
    "PSA": "Public Storage",
    "PSX": "Phillips 66",
    "PTC": "PTC Inc.",
    "PWR": "Quanta Services Inc.",
    "PYPL": "PayPal Holdings Inc.",
    "QCOM": "QUALCOMM Inc.",
    "QRVO": "Qorvo Inc.",
    "R": "Ryder System Inc.",
    "RAI": "Renaissance Technologies",
    "RCL": "Royal Caribbean Cruises Ltd.",
    "REG": "Regency Centers Corporation",
    "REGN": "Regeneron Pharmaceuticals Inc.",
    "RHI": "Robert Half International Inc.",
    "RJF": "Raymond James Financial Inc.",
    "RL": "Ralph Lauren Corporation",
    "RMD": "ResMed Inc.",
    "ROK": "Rockwell Automation Inc.",
    "ROL": "Rollins Inc.",
    "ROP": "Roper Technologies Inc.",
    "ROST": "Ross Stores Inc.",
    "RS": "Reliance Steel & Aluminum Co.",
    "RTX": "RTX Corporation",
    "RIVN": "Rivian Automotive Inc.",
    "SBAC": "SBA Communications Corporation",
    "SBUX": "Starbucks Corporation",
    "SCHW": "Charles Schwab Corporation",
    "SEDG": "SolarEdge Technologies Inc.",
    "SEE": "Sealed Air Corporation",
    "SHW": "Sherwin-Williams Company",
    "SIRI": "Sirius XM Holdings Inc.",
    "SJM": "J.M. Smucker Company",
    "SLB": "Schlumberger Limited",
    "SNA": "Snap-on Incorporated",
    "SNAP": "Snap Inc.",
    "SNPS": "Synopsys Inc.",
    "SO": "Southern Company",
    "SPG": "Simon Property Group Inc.",
    "SPGI": "S&P Global Inc.",
    "SRE": "Sempra Energy",
    "STZ": "Constellation Brands Inc.",
    "SWK": "Stanley Black & Decker Inc.",
    "SWKS": "Skyworks Solutions Inc.",
    "SYF": "Synchrony Financial",
    "SYK": "Stryker Corporation",
    "SYY": "Sysco Corporation",
    "T": "AT&T Inc.",
    "TAP": "Molson Coors Beverage Company",
    "TCF": "TCF Financial Corporation",
    "TGT": "Target Corporation",
    "TIF": "Tiffany & Co.",
    "TJX": "TJX Companies Inc.",
    "TMO": "Thermo Fisher Scientific Inc.",
    "TMUS": "T-Mobile US Inc.",
    "TROW": "T. Rowe Price Group Inc.",
    "TRV": "Travelers Companies Inc.",
    "TSCO": "Tractor Supply Company",
    "TSLA": "Tesla Inc.",
    "TSN": "Tyson Foods Inc.",
    "TT": "Trane Technologies plc",
    "TTWO": "Take-Two Interactive Software Inc.",
    "TWTR": "Twitter Inc.",
    "TXN": "Texas Instruments Inc.",
    "TXT": "Textron Inc.",
    "TYL": "Tyler Technologies Inc.",
    "UA": "Under Armour Inc.",
    "UAA": "Under Armour Inc.",
    "UAL": "United Airlines Holdings Inc.",
    "UDR": "UDR Inc.",
    "UHS": "Universal Health Services Inc.",
    "ULTA": "Ulta Beauty Inc.",
    "UNH": "UnitedHealth Group Inc.",
    "UNM": "Unum Group",
    "UNP": "Union Pacific Corporation",
    "UPS": "United Parcel Service Inc.",
    "URI": "United Rentals Inc.",
    "USB": "U.S. Bancorp",
    "V": "Visa Inc.",
    "VFC": "V.F. Corporation",
    "VICI": "VICI Properties Inc.",
    "VLO": "Valero Energy Corporation",
    "VMC": "Vulcan Materials Company",
    "VRSK": "Verisk Analytics Inc.",
    "VRSN": "VeriSign Inc.",
    "VRTX": "Vertex Pharmaceuticals Incorporated",
    "VTR": "Ventas Inc.",
    "VZ": "Verizon Communications Inc.",
    "W": "Weyerhaeuser Company",
    "WAB": "Westinghouse Air Brake Technologies Corporation",
    "WAT": "Waters Corporation",
    "WBA": "Walgreens Boots Alliance Inc.",
    "WBD": "Warner Bros. Discovery Inc.",
    "WCG": "WellCare Health Plans Inc.",
    "WDC": "Western Digital Corporation",
    "WEC": "WEC Energy Group Inc.",
    "WELL": "Welltower Inc.",
    "WFC": "Wells Fargo & Company",
    "WHR": "Whirlpool Corporation",
    "WLTW": "Willis Towers Watson Public Limited Company",
    "WM": "Waste Management Inc.",
    "WMB": "Williams Companies Inc.",
    "WMT": "Walmart Inc.",
    "WRB": "W.R. Berkley Corporation",
    "WRK": "WestRock Company",
    "WST": "West Pharmaceutical Services Inc.",
    "WTW": "Willis Towers Watson",
    "WY": "Weyerhaeuser Company",
    "WYNN": "Wynn Resorts Limited",
    "X": "United States Steel Corporation",
    "XEL": "Xcel Energy Inc.",
    "XLB": "Materials Select Sector SPDR Fund",
    "XLC": "Communication Services Select Sector SPDR Fund",
    "XLE": "Energy Select Sector SPDR Fund",
    "XLF": "Financial Select Sector SPDR Fund",
    "XLI": "Industrial Select Sector SPDR Fund",
    "XLK": "Technology Select Sector SPDR Fund",
    "XLP": "Consumer Staples Select Sector SPDR Fund",
    "XLRE": "Real Estate Select Sector SPDR Fund",
    "XLU": "Utilities Select Sector SPDR Fund",
    "XLV": "Health Care Select Sector SPDR Fund",
    "XLY": "Consumer Discretionary Select Sector SPDR Fund",
    "XOM": "Exxon Mobil Corporation",
    "XRAY": "DENTSPLY SIRONA Inc.",
    "XYL": "Xylem Inc.",
    "YUM": "Yum! Brands Inc.",
    "ZBH": "Zimmer Biomet Holdings Inc.",
    "ZBRA": "Zebra Technologies Corporation",
    "ZION": "Zions Bancorporation N.A.",
    "ZTS": "Zoetis Inc.",
}


def _load_sp500_map() -> dict[str, str]:
    path = os.path.join(os.path.dirname(__file__), "..", "..", "data", "sp500.json")
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    return {}


def get_sp500_map() -> Dict[str, str]:
    """
    Returns the S&P 500 ticker → company name map.
    Uses a static list to avoid Wikipedia scraping issues (403 Forbidden).
    """
    global _SP500_MAP
    if _SP500_MAP:
        return _SP500_MAP

    # Use static map instead of scraping Wikipedia
    _SP500_MAP = _load_sp500_map()
    logger.info(f"✅ Loaded {len(_SP500_MAP)} S&P 500 tickers from data/sp500.json")

    return _SP500_MAP


def get_company_name(ticker: str) -> str:
    """Return the company name for a ticker, or the ticker itself as fallback."""
    sp500 = get_sp500_map()
    return sp500.get(ticker.upper(), ticker.upper())


def get_all_sp500_tickers() -> List[str]:
    """Return the full list of S&P 500 ticker symbols."""
    return list(get_sp500_map().keys())


class NewsService:
    def __init__(self):
        self.api_key = settings.NEWSAPI_KEY

    async def fetch_articles(self, ticker: str, limit: int = 10) -> List[Dict]:
        """
        Fetch recent financial news articles for a ticker from NewsAPI.
        Uses the company name from the S&P 500 list for a better search query.
        """
        if not self.api_key:
            raise ValueError("NEWSAPI_KEY is not set in .env")

        company_name = get_company_name(ticker.upper())

        # Use company name if it differs from ticker (more readable queries)
        query = company_name if company_name != ticker.upper() else ticker.upper()

        # Free tier supports last 30 days; use 7 for freshness
        from_date = (datetime.now(timezone.utc) - timedelta(days=7)).strftime(
            "%Y-%m-%d"
        )

        params = {
            "q": f"{query} stock",
            "language": "en",
            "sortBy": "publishedAt",
            "pageSize": min(limit, 100),
            "from": from_date,
            "apiKey": self.api_key,
        }

        async with httpx.AsyncClient(timeout=15) as client:
            response = await client.get(NEWSAPI_BASE, params=params)

        if response.status_code != 200:
            logger.error(f"NewsAPI error {response.status_code}: {response.text}")
            raise ValueError(f"NewsAPI request failed: {response.status_code}")

        data = response.json()
        if data.get("status") != "ok":
            raise ValueError(f"NewsAPI error: {data.get('message', 'unknown')}")

        articles = data.get("articles", [])
        logger.info(f"📰 {ticker} ({company_name}): fetched {len(articles)} articles")
        return articles

    def parse_article(self, raw: Dict, ticker: str) -> Dict:
        """Normalise a raw NewsAPI article into a clean dict."""
        published_raw = raw.get("publishedAt", "")
        try:
            published_at = datetime.fromisoformat(published_raw.replace("Z", "+00:00"))
            published_at = published_at.replace(tzinfo=None)
        except Exception:
            published_at = datetime.now(timezone.utc)

        return {
            "ticker": ticker.upper(),
            "title": raw.get("title") or "",
            "description": raw.get("description") or "",
            "url": raw.get("url") or "",
            "source": raw.get("source", {}).get("name") or "Unknown",
            "published_at": published_at,
        }
